# Terraform Plan Pipeline
trigger:
  branches:
    include:
      - main
      - develop

variables:
  - group: terraform-prod-variables
  - name: TF_VERSION
    value: '1.10.3'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Validate
    displayName: 'Validate Terraform'
    jobs:
      - job: ValidateCode
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: $(TF_VERSION)
          
          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: 'environments/canadacentral/prod'
